#-*- mode: org -*-
#+STARTUP: showall

* My Emacs Config

** Options & minor modes

*** General

**** Disabling GUI elements
#+begin_src elisp
  (menu-bar-mode 0)
  (tool-bar-mode -1)
  (scroll-bar-mode 0)
#+end_src

**** Disable backup files
#+begin_src elisp
  (setq-default make-backup-files nil)
#+end_src

**** Disable bell
#+begin_src elisp
  (setq-default ring-bell-function 'ignore)
#+end_src

**** Disable wrap
#+begin_src elisp
  (setq-default truncate-lines t)
#+end_src

**** Font
#+begin_src elisp
  (set-face-attribute 'default nil :font "SFMono Nerd Font-10")
  (add-to-list 'default-frame-alist '(font . "SFMono Nerd Font-10"))
#+end_src

**** Delete selection
#+begin_quote
When Delete Selection mode is enabled, typed text replaces the selection
if the selection is active. Otherwise, typed text is just inserted at
point regardless of any selection.
#+end_quote
#+begin_src elisp
  (delete-selection-mode t)
#+end_src

**** Completion
#+begin_src elisp
  (setq-default tab-always-indent 'complete)
  (fido-mode t)
  (fido-vertical-mode t)
#+end_src

**** Line numbers
#+begin_src elisp
  (global-display-line-numbers-mode 1)
#+end_src

**** Pulse region when deactivated
#+begin_src elisp
  (add-hook
   'deactivate-mark-hook
   (lambda () (pulse-momentary-highlight-region (region-beginning) (region-end))))
#+end_src

**** Modeline
#+begin_src elisp
  ;; Modeline
  (defun my-modified-status ()
    "Returns Saved or Not saved"
    (if (buffer-modified-p)
        (propertize "*" 'face '(:weight bold))
      "-"))

  (defun my-buffer-name ()
    "Returns the buffer name, but with `propertize`"
    (propertize (buffer-name) 'face '(:foreground "#c397d8")))

  (setq-default mode-line-format
  	      (list
  	       " "
  	       '(:eval (my-modified-status))
  	       " | "
  	       '(:eval (my-buffer-name))))

#+end_src


*** Org-mode
#+begin_src elisp
  (setq-default org-statup-indented t)
#+end_src


** Plugins

**** MELPA
#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src

**** Theme
#+begin_src elisp
  (use-package afternoon-theme
    :ensure t
    :config
    (load-theme 'afternoon t))
#+end_src

**** Autosave
#+begin_src elisp
  (use-package super-save
    :ensure t
    :config
    (super-save-mode +1))
#+end_src


** Keymaps

*** Core keymaps
These keymaps cannot be overwritten by any major mode.

Create the mode map.
#+begin_src elisp
  (defvar core-keymaps-mode-map (make-sparse-keymap))
#+end_src

**** Buffer/file operations
#+begin_src elisp
  (defun open-config () (interactive) (find-file "~/.emacs.d/init-org.org"))
  (define-key core-keymaps-mode-map (kbd "C-x c") 'open-config)
#+end_src

Open file:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-o") 'find-file)
#+end_src

Save buffer:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-s") 'save-buffer)
#+end_src

Switch to buffer:
#+begin_src elisp
  (keymap-global-set "C-b" 'switch-to-buffer)
#+end_src

**** Cursor movement
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "M-h") 'left-char)
  (define-key core-keymaps-mode-map (kbd "M-j") 'next-line)
  (define-key core-keymaps-mode-map (kbd "M-k") 'previous-line)
  (define-key core-keymaps-mode-map (kbd "M-l") 'right-char)
#+end_src

**** Cursor movement (large motions)
src_elisp{smart-beginning-of-line} moves the cursor to the beginning of the text. If already there, at the beginning of the line.
#+begin_src elisp
  (defun smart-beginning-of-line ()
    (interactive)
    (let ((old-point (point)))
      (back-to-indentation)
      (if (= old-point (point))
  	(beginning-of-line))))

  (define-key core-keymaps-mode-map (kbd "M-H") 'smart-beginning-of-line)
  (define-key core-keymaps-mode-map (kbd "M-J") 'forward-paragraph)
  (define-key core-keymaps-mode-map (kbd "M-K") 'backward-paragraph)
  (define-key core-keymaps-mode-map (kbd "M-L") 'end-of-line)
  (define-key core-keymaps-mode-map (kbd "M-w") 'forward-word)
#+end_src

**** Vim-style character find (f)
#+begin_src elisp
  (defun one-char-search-forward ()
    (interactive)
    (message "Waiting or a key...")
    (let ((key (read-char)))
      (search-forward (byte-to-string key))))

  (defun one-char-search-backward ()
    (interactive)
    (message "Waiting or a key...")
    (let ((key (read-char)))
      (search-backward (byte-to-string key))))

  (define-key core-keymaps-mode-map (kbd "M-f") 'one-char-search-forward)
  (define-key core-keymaps-mode-map (kbd "M-F") 'one-char-search-backward)
#+end_src

**** New line above/below
#+begin_src elisp
  (defun newline-above ()
    (interactive)
    (beginning-of-line)
    (newline)
    (previous-line)
    (indent-according-to-mode))

  (defun newline-below ()
    (interactive)
    (end-of-line)
    (newline-and-indent))

  (define-key core-keymaps-mode-map (kbd "M-O") 'newline-above)
  (define-key core-keymaps-mode-map (kbd "M-o") 'newline-below)
#+end_src

**** Scroll a half-page
#+begin_src elisp
  (defun scroll-up-half-page ()
    (interactive)
    (scroll-up (/ (window-body-height) 2)))
  
  (defun scroll-down-half-page ()
    (interactive)
    (scroll-down (/ (window-body-height) 2)))

  (define-key core-keymaps-mode-map (kbd "C-M-j") 'scroll-up-half-page)
  (define-key core-keymaps-mode-map (kbd "C-M-k") 'scroll-down-half-page)
#+end_src

**** Undo/Redo
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-u") 'undo-only)
  (define-key core-keymaps-mode-map (kbd "C-r") 'undo-redo)
#+end_src

**** Splits
#+begin_src elisp
  (defun split-window-plus ()
    (interactive)
    (split-window-horizontally)
    (windmove-right))

  (defun split-window-minus ()
    (interactive)
    (split-window-vertically)
    (windmove-down))

  (define-key core-keymaps-mode-map (kbd "M-+") 'split-window-plus)
  (define-key core-keymaps-mode-map (kbd "M-_") 'split-window-minus)
#+end_src

**** Window commands
#+begin_src elisp
  (define-prefix-command 'window-map)
  (define-key core-keymaps-mode-map (kbd "C-w") 'window-map)
  (define-key window-map (kbd "C-w") 'delete-other-windows)
  (define-key window-map (kbd "q") 'delete-window)
  (define-key window-map (kbd "h") 'windmove-left)
  (define-key window-map (kbd "j") 'windmove-down)
  (define-key window-map (kbd "k") 'windmove-up)
  (define-key window-map (kbd "l") 'windmove-right)
#+end_src

**** Selection commands
#+begin_src elisp
  (defun select-inside-line ()
    (interactive)
    (end-of-line)
    (set-mark (point))
    (beginning-of-line))

  (define-key core-keymaps-mode-map (kbd "C-v") 'set-mark-command)

  (define-prefix-command 'marking)
  (define-key core-keymaps-mode-map (kbd "M-m") 'marking)
  (define-key marking (kbd "w") 'mark-word)
  (define-key marking (kbd "l") 'select-inside-line)
  (define-key marking (kbd "p") 'mark-paragraph)
#+end_src

**** Searching
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-f") 'isearch-forward)
  (define-key core-keymaps-mode-map (kbd "C-S-f") 'isearch-backward)
  (define-key isearch-mode-map (kbd "<return>") 'isearch-repeat-forward)
  (define-key isearch-mode-map (kbd "S-<return>") 'isearch-repeat-backward)
  (define-key isearch-mode-map (kbd "<escape>") 'isearch-exit)
#+end_src

**** Yank/Paste
#+begin_src elisp
  ;; 
  (define-key core-keymaps-mode-map (kbd "C-y") 'kill-ring-save)
  (define-key core-keymaps-mode-map (kbd "C-p") 'yank)
  (define-key core-keymaps-mode-map (kbd "M-p") 'yank-pop)

  (defun copy-line ()
    (interactive)
    (select-inside-line)
    (kill-ring-save 0 0 t))

  (defun copy-paragraph ()
    (interactive)
    (mark-paragraph)
    (kill-ring-save 0 0 t))

  (define-prefix-command 'copying)
  (define-key core-keymaps-mode-map (kbd "M-y") 'copying)
  (define-key copying (kbd "l") 'copy-line)
  (define-key copying (kbd "p") 'copy-paragraph)
#+end_src

**** Misc
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-j") (lambda () (interactive) (next-line) (join-line)))
#+end_src

**** Creating the core keymaps minor mode
#+begin_src elisp
(define-minor-mode core-keymaps-mode
  "All the core keymaps"
  :keymap core-keymaps-mode-map
  :lighter "Core"
  :global t)

(core-keymaps-mode 1)
#+end_src


*** icomplete
#+begin_src elisp
  (define-key icomplete-minibuffer-map (kbd "<tab>") 'icomplete-forward-completions)
  (define-key icomplete-minibuffer-map (kbd "<backtab>") 'icomplete-backward-completions)
  (define-key icomplete-minibuffer-map (kbd "<return>") (lambda () (interactive) (icomplete-force-complete) (icomplete-ret)))
  (define-key icomplete-minibuffer-map (kbd "C-<return>") 'icomplete-ret)
#+end_src

*** Commenting
(Un)Comments the active region if it exists. Otherwise (un)comments the current line.
#+begin_src elisp
  (defun comment-line-or-selection ()
    (interactive)
    (when (not (region-active-p))
      (select-inside-line))
    (comment-or-uncomment-region (region-beginning) (region-end)))

  (keymap-global-set "C-/" 'comment-line-or-selection)
#+end_src
