#-*- mode: org -*-
#+STARTUP: content
#+PROPERTY: header-args :results none

* TODO
- forward-word etc functions
  - C-<tab> for cycling buffers + showing all buffer orders for a window in the modeline or something
  - better list bullets (from scratch)
  - resizing windows
  - moving windows around
  - marking inside "", (), [] etc
  - repeat M-f action for last character

* Options & minor modes
** General
*** Disabling GUI elements
#+begin_src elisp
  (menu-bar-mode 0)
  (tool-bar-mode -1)
  (scroll-bar-mode 0)
  (setq inhibit-splash-screen t)
#+end_src

*** Disable backup files
#+begin_src elisp
  (setq-default make-backup-files nil)
#+end_src

*** Disable bell
#+begin_src elisp
  (setq-default ring-bell-function 'ignore)
#+end_src

*** Disable wrap
#+begin_src elisp
  (setq-default truncate-lines t)
#+end_src

*** Font
#+begin_src elisp
  (set-face-attribute 'default nil :font "SFMono Nerd Font-10")
  (add-to-list 'default-frame-alist '(font . "SFMono Nerd Font-10"))
#+end_src

*** Delete selection
#+begin_quote
"When Delete Selection mode is enabled, typed text replaces the selection
if the selection is active. Otherwise, typed text is just inserted at
point regardless of any selection."
#+end_quote
#+begin_src elisp
  (delete-selection-mode t)
#+end_src

*** Completion
#+begin_src elisp
  (setq-default tab-always-indent 'complete)
  (fido-mode t)
  (fido-vertical-mode t)
#+end_src

*** Line numbers
#+begin_src elisp
  (global-display-line-numbers-mode 1)
#+end_src

*** Pulse region when deactivated
#+begin_src elisp
  (add-hook
   'deactivate-mark-hook
   (lambda () (pulse-momentary-highlight-region (region-beginning) (region-end))))
#+end_src

*** Modeline
#+begin_src elisp
  ;; Modeline
  (defun my-modified-status ()
    "Returns Saved or Not saved"
    (if (buffer-modified-p)
        (propertize "*" 'face '(:weight bold))
      "-"))

  (defun my-buffer-name ()
    "Returns the buffer name, but with `propertize`"
    (propertize (buffer-name) 'face '(:foreground "#c397d8")))

  (setq-default mode-line-format
                (list
                 " "
                 '(:eval (my-modified-status))
                 " | "
                 '(:eval (my-buffer-name))))

#+end_src
*** Misc
Start in fullscreen
#+begin_src elisp
  (add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+end_src
** Org-mode
*** General options
Disable confirmation for src block evaluation.
#+begin_src elisp
  (setq org-confirm-babel-evaluate nil)
  (setq org-fontify-quote-and-verse-blocks t)
#+end_src

*** Headings
Give each heading a shade of grey, based on importance.
#+begin_src elisp
  (defun set-org-heading-fonts ()
    (set-face-attribute 'org-level-1 nil :family "DejaVu Sans" :height 1.8 :weight 'semi-bold :foreground "#ffffff")
    (set-face-attribute 'org-level-2 nil :family "DejaVu Sans" :height 1.6 :weight 'semi-bold :foreground "#dddddd")
    (set-face-attribute 'org-level-3 nil :family "DejaVu Sans" :height 1.4 :weight 'semi-bold :foreground "#bbbbbb")
    (set-face-attribute 'org-level-4 nil :family "DejaVu Sans" :height 1.2 :weight 'semi-bold :foreground "#999999"))
#+end_src

*** Heading numbers
By default the face of the numbers inherits the face of the headline and so multiplies the font size again, which we don't want.
We need to create a face that sets height to 1.0 so that the numbers don t get scaled up even more.
#+begin_src elisp
  (defface my-org-num-blank-face '((t nil)) "Heading number face")
  (setq org-num-face 'my-org-num-blank-face)
#+end_src
*** Other fonts
#+begin_src elisp
  (defun set-other-org-fonts ()
    (set-face-attribute 'variable-pitch nil :family "DejaVu Sans" :height 1.0)
    (set-face-attribute 'org-block nil :family "SFMono Nerd Font" :height 1.0 :background "#12131b")
    (set-face-attribute 'org-meta-line nil :family "SFMono Nerd Font" :height 0.8)
    (set-face-attribute 'org-hide nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-quote nil :inherit 'variable-pitch :slant 'italic))
#+end_src
    
*** Indentation
#+begin_src elisp
  (setq org-adapt-indentation t)
  (setq org-indent-indentation-per-level 2)
#+end_src
*** Org hook
#+begin_src elisp
  (add-hook
   'org-mode-hook
   (lambda ()
     (display-line-numbers-mode 0)
     (visual-line-mode t)
     (org-num-mode t)
     (variable-pitch-mode t)
     (org-indent-mode t)
     (set-org-heading-fonts)
     (set-other-org-fonts)))
#+end_src
** Terminal
Don't ask before  killing active process:
#+begin_src elisp
  (setq confirm-kill-process nil)
#+end_src

Disable line numbers:
#+begin_src elisp
  (add-hook
   'term-mode-hook
   (lambda ()
     (display-line-numbers-mode 0)))
#+end_src
* Plugins
** MELPA
#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src

** Theme
#+begin_src elisp
  (use-package afternoon-theme
    :ensure t
    :config
    (load-theme 'afternoon t))
#+end_src

** Autosave
#+begin_src elisp
  (use-package super-save
    :ensure t
    :config
    (super-save-mode +1))
#+end_src

* Keymaps
** Core keymaps
These keymaps cannot be overwritten by any major mode.

Create the mode map.
#+begin_src elisp
  (defvar core-keymaps-mode-map (make-sparse-keymap))
#+end_src

*** Buffer/file operations
#+begin_src elisp
  (defun open-config () (interactive) (find-file "~/.emacs.d/init-org.org"))
  (define-key core-keymaps-mode-map (kbd "C-x c") 'open-config)
#+end_src

Open file:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-o") 'find-file)
#+end_src

Open dired:
#+begin_src elisp
  (defun open-dired-here ()
    (interactive)
    (dired "."))

  (define-key core-keymaps-mode-map (kbd "C-S-o") 'open-dired-here)
#+end_src

Save buffer:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-s") 'save-buffer)
#+end_src

Switch to buffer:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-b") 'switch-to-buffer)
#+end_src
Kill buffer:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-S-k") 'kill-current-buffer)
#+end_src

*** Cursor movement
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "M-h") 'left-char)
  (define-key core-keymaps-mode-map (kbd "M-j") 'next-line)
  (define-key core-keymaps-mode-map (kbd "M-k") 'previous-line)
  (define-key core-keymaps-mode-map (kbd "M-l") 'right-char)
#+end_src

*** Cursor movement (large motions)
src_elisp{smart-beginning-of-line} moves the cursor to the beginning of the text. If already there, at the beginning of the line.
#+begin_src elisp
  (defun smart-beginning-of-line ()
    (interactive)
    (let ((old-point (point)))
      (back-to-indentation)
      (if (= old-point (point))
          (beginning-of-line))))

  (define-key core-keymaps-mode-map (kbd "M-H") 'smart-beginning-of-line)
  (define-key core-keymaps-mode-map (kbd "M-J") 'forward-paragraph)
  (define-key core-keymaps-mode-map (kbd "M-K") 'backward-paragraph)
  (define-key core-keymaps-mode-map (kbd "M-L") 'end-of-line)
#+end_src

Forward/backward word with custom word delimiters:
#+begin_src elisp
  (defun my-forward-word ()
    (interactive))
  (defun my-backward-word ()
    (interactive))
  
  (define-key core-keymaps-mode-map (kbd "M-w") 'forward-word)
#+end_src

Push mark on forward/backward paragraph.
#+begin_src elisp
  (advice-add 'forward-paragraph :before (lambda (&rest _args) (push-mark nil t nil)))
#+end_src

*** Vim-style character find (f)
#+begin_src elisp
  (defun one-char-search-forward ()
    (interactive)
    (message "Waiting or a key...")
    (let ((key (read-char)))
      (search-forward (byte-to-string key))))

  (defun one-char-search-backward ()
    (interactive)
    (message "Waiting or a key...")
    (let ((key (read-char)))
      (search-backward (byte-to-string key))))

  (define-key core-keymaps-mode-map (kbd "M-f") 'one-char-search-forward)
  (define-key core-keymaps-mode-map (kbd "M-F") 'one-char-search-backward)
#+end_src

*** New line above/below
#+begin_src elisp
  (defun newline-above ()
    (interactive)
    (beginning-of-line)
    (newline)
    (previous-line)
    (indent-according-to-mode))

  (defun newline-below ()
    (interactive)
    (end-of-line)
    (newline-and-indent))

  (define-key core-keymaps-mode-map (kbd "M-O") 'newline-above)
  (define-key core-keymaps-mode-map (kbd "M-o") 'newline-below)
#+end_src

*** Scroll a half-page
#+begin_src elisp
  (defun scroll-up-half-page ()
    (interactive)
    (push-mark nil t nil)
    (previous-line (/ (window-body-height) 2))
    (recenter))

  (defun scroll-down-half-page ()
    (interactive)
    (push-mark nil t nil)
    (next-line (/ (window-body-height) 2))
    (recenter))

  (define-key core-keymaps-mode-map (kbd "C-M-j") 'scroll-down-half-page)
  (define-key core-keymaps-mode-map (kbd "C-M-k") 'scroll-up-half-page)
#+end_src

*** Undo/Redo
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-u") 'undo-only)
  (define-key core-keymaps-mode-map (kbd "C-r") 'undo-redo)
#+end_src

*** Splits
#+begin_src elisp
  (defun split-window-plus ()
    (interactive)
    (split-window-horizontally)
    (windmove-right))

  (defun split-window-minus ()
    (interactive)
    (split-window-vertically)
    (windmove-down))

  (define-key core-keymaps-mode-map (kbd "M-+") 'split-window-plus)
  (define-key core-keymaps-mode-map (kbd "M-_") 'split-window-minus)
#+end_src

*** Window commands
#+begin_src elisp
  (define-prefix-command 'window-map)
  (define-key core-keymaps-mode-map (kbd "C-w") 'window-map)
  (define-key window-map (kbd "C-w") 'delete-other-windows)
  (define-key window-map (kbd "q") 'delete-window)
  (define-key window-map (kbd "h") 'windmove-left)
  (define-key window-map (kbd "j") 'windmove-down)
  (define-key window-map (kbd "k") 'windmove-up)
  (define-key window-map (kbd "l") 'windmove-right)
#+end_src

*** Selection commands
#+begin_src elisp
  (defun select-inside-line ()
    (interactive)
    (end-of-line)
    (set-mark (point))
    (beginning-of-line))

  (define-key core-keymaps-mode-map (kbd "M-v") 'set-mark-command)
  (define-key core-keymaps-mode-map (kbd "M-s") 'mark-sexp)

  (define-prefix-command 'marking)
  (define-key core-keymaps-mode-map (kbd "M-m") 'marking)
  (define-key marking (kbd "w") 'mark-word)
  (define-key marking (kbd "l") 'select-inside-line)
  (define-key marking (kbd "p") 'mark-paragraph)
  (define-key marking (kbd "a") 'mark-whole-buffer)
#+end_src

*** Searching
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-f") 'isearch-forward)
  (define-key core-keymaps-mode-map (kbd "C-S-f") 'isearch-backward)
  (define-key isearch-mode-map (kbd "<return>") 'isearch-repeat-forward)
  (define-key isearch-mode-map (kbd "S-<return>") 'isearch-repeat-backward)
  (define-key isearch-mode-map (kbd "<escape>") 'isearch-exit)
#+end_src

*** Yank/Paste
Core commands and prefix:
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-y") 'kill-ring-save)
  (define-key core-keymaps-mode-map (kbd "C-p") 'yank)
  (define-key core-keymaps-mode-map (kbd "M-p") 'yank-pop)
  (define-prefix-command 'copying)
  (define-key core-keymaps-mode-map (kbd "M-y") 'copying)
#+end_src

Copy line:
#+begin_src elisp
  (defun copy-line ()
    (interactive)
    (select-inside-line)
    (kill-ring-save 0 0 t))
  
  (define-key copying (kbd "l") 'copy-line)
#+end_src

Copy paragraph:
#+begin_src elisp
  (defun copy-paragraph ()
    (interactive)
    (mark-paragraph)
    (kill-ring-save 0 0 t))
  
  (define-key copying (kbd "p") 'copy-paragraph)
#+end_src

Copy whole buffer:
#+begin_src elisp
  (defun copy-whole-buffer ()
    (interactive)
    (mark-whole-buffer)
    (kill-ring-save 0 0 t))

  (define-key copying (kbd "a") 'copy-whole-buffer)
#+end_src

*** Delete
*** Misc
#+begin_src elisp
  (define-key core-keymaps-mode-map (kbd "C-j") (lambda () (interactive) (next-line) (join-line)))
  (define-key core-keymaps-mode-map (kbd "C-M-o") 'pop-global-mark)  
#+end_src

*** Create the core keymaps minor mode
#+begin_src elisp
  (define-minor-mode core-keymaps-mode
    "All the core keymaps"
    :keymap core-keymaps-mode-map
    :lighter "Core"
    :global t)

  (core-keymaps-mode 1)
#+end_src

*** Toggle terminal
#+begin_src elisp
  (defun term-exists ()
    (when (eq (get-buffer "*terminal*") nil) nil)
    t)

  (defun start-term ()
    (interactive)
    (term "/usr/bin/zsh"))

  (defun switch-to-term ()
    (interactive)
    (switch-to-buffer "*terminal*" nil t))

  (defun toggle-term ()
    (interactive)
    (if (eq (current-buffer) (get-buffer "*terminal*"))
        (switch-to-buffer nil nil t)
      (if (term-exists)
  	(switch-to-term)
        (start-term))))

  (define-key core-keymaps-mode-map (kbd "C-`") 'toggle-term)
#+end_src
** icomplete
#+begin_src elisp
  (define-key icomplete-minibuffer-map (kbd "<tab>") 'icomplete-forward-completions)
  (define-key icomplete-minibuffer-map (kbd "<backtab>") 'icomplete-backward-completions)
  (define-key icomplete-minibuffer-map (kbd "<return>") 'icomplete-force-complete-and-exit)
  (define-key icomplete-minibuffer-map (kbd "C-<return>") 'icomplete-force-complete)
#+end_src

** Commenting
(Un)Comments the active region if it exists. Otherwise (un)comments the current line.
#+begin_src elisp
  (defun comment-line-or-selection ()
    (interactive)
    (when (not (region-active-p))
      (select-inside-line))
    (comment-or-uncomment-region (region-beginning) (region-end)))

  (keymap-global-set "C-/" 'comment-line-or-selection)
#+end_src

** Org
Keymaps for:
- create source block
- create quote
- execute code block
- execute buffer
#+begin_src elisp
  (defun insert-org-src ()
    (interactive)
    (org-insert-structure-template "src"))

  (defun insert-org-quote ()
    (interactive)
    (org-insert-structure-template "quote"))

  (with-eval-after-load "org"
    (define-key org-mode-map (kbd "C-c s") 'insert-org-src)
    (define-key org-mode-map (kbd "C-c q") 'insert-org-quote)
    (define-key org-mode-map (kbd "C-<return>") 'org-babel-execute-src-block))
#+end_src

** Dired
#+begin_src elisp
  (define-key dired-mode-map (kbd "h") 'left-char)
  (define-key dired-mode-map (kbd "j") 'next-line)
  (define-key dired-mode-map (kbd "k") 'previous-line)
  (define-key dired-mode-map (kbd "l") 'right-char)
  (define-key dired-mode-map (kbd "+") 'dired-create-empty-file)
  (define-key dired-mode-map (kbd "C-+") 'dired-create-directory)
  (define-key dired-mode-map (kbd "<backspace>") 'dired-up-directory)
#+end_src
